version: '3'
services:
   product-app:
      container_name: product-app
      image: mabaloch/productservice
      restart: on-failure
      ports:
         - 10666:5000
      environment:
         WAIT_HOSTS: mysql:3306
      depends_on:
         - docker-mysql
         - coupon-app
   coupon-app:
      container_name: coupon-app
      image: mabaloch/couponservice
      restart: on-failure
      ports:
         - 10555:5000
      environment:
         WAIT_HOSTS: mysql:3306
      depends_on:
         - docker-mysql
   docker-mysql:
      container_name: docker-mysql
      image: mysql
      restart: always
      environment:
         MYSQL_DATABASE: mydb
         MYSQL_ROOT_PASSWORD: 12345678
         MYSQL_ROOT_HOST: '%'
      volumes:
         - ./sql:/docker-entrypoint-initdb.d
      ports:
         - "6666:3306"
      healthcheck:
         test: "/usr/bin/mysql --usr=root --password=12345678 --execute \"SHOW DATABASES \""
         interval: 4s
         timeout: 20s
         retries: 5